server:
  port: 8080
spring:
  application:
    name: gateway
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: ms1
#          uri: http://localhost:8081
#          predicates:
#            - Path=/ms1/**
#        - id: ms2
#          uri: http://localhost:8082
#          predicates:
#            - Path=/ms2/**


# eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

